/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zg_jni_demo_Demo */

#ifndef _Included_com_zg_jni_demo_Demo
#define _Included_com_zg_jni_demo_Demo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zg_jni_demo_Demo
 * Method:    init
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_zg_jni_demo_Demo_init
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
